auth_endpoint_host:      https://www.facebook.com
auth_endpoint_path:      /v2.12/dialog/oauth
token_endpoint_host:     https://graph.facebook.com
token_endpoint_path:     /v2.12/oauth/access_token
token_debug_path:        /debug_token
userinfo_endpoint_host:  https://graph.facebook.com
app_id:                  --your-app-id--
app_secret:              --your-app-secret--
redirect_uri:            https://--your-redirect-uri--
